# 默认配置 - 通用设置
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  web:
    resources:
      static-locations: classpath:/static/
    mvc:
      static-path-pattern: /static/**

  # 通用JPA配置
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

# 通用应用配置
app:
  name: AstraLint
  version: 1.0.0
  description: AI-powered code review system
